[env:lolin_c3_mini]
platform   = espressif32@6.9.0
board      = lolin_c3_mini
framework  = arduino


#! Common settings for all environments
monitor_speed = 115200


#! Main environment for development
build_flags = -DCORE_DEBUG_LEVEL=0

#! Common libraries for all environments
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3
    adafruit/Adafruit SHTC3 Library @ ^1.0.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
    knolleary/PubSubClient @ ^2.8.0
    bblanchon/ArduinoJson@^6.21.0
    dfrobot/DFRobot_ENS160
